title: Heritage Connector
author:
  name: 
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  Transforming text into data to extract meaning and make connections.
show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
theme: jekyll-theme-cayman

plugins:
 - jekyll-feed
 - jekyll-seo-tag
